### PR TITLE
Add github actions CI to test if it builds

### PR DESCRIPTION
**Pull request by adminfriso**

### CODE REVIEW

**Comment by sebleedelisle** [comment]
Thanks!

**Comment by sebleedelisle** [comment]
Oh and let me know what else I need to do on the GitHub set up to make this work 😀

**Comment by adminfriso** [comment]
got to run now, ill comment and document tonight or tomorrow

**Comment by adminfriso** [comment]
but it should work out of the box. go and watch the actions button right from the pullrequest button :)

**Comment by adminfriso** [comment]
So usually the actions start automatically, and they run on each push. The first action might need to be manually triggered. so please check it out and see if you have any start button available. Else try to push something. 
The actions are found in the .github folder and all active actions can be found in the workflow folder.

These actions are heavily inspired on the openframeworks build actions, as I tried to build one using circle CI but this turned out to be much faster to build. And since this is an opensource project there is no limit on the hours ran before billing. (from the top of my head, to make sure check it out on the actions page (https://docs.github.com/en/actions))

The action pulls openframeworks, and then pulls ofxlaser to the addons folder. 
We replace the examples/templates/emptyExample with example_HelloLaser and then continue the setup as defined by openframeworks.

Depending on the way openframeworks does it gives an extra benifit, in the case of an update and the builds fail while the build should work, we can check out if something is changed in openframeworks/openframeworks. 

Right now the actions for vs2022 and the mac-makefile are disabled as they fail on building.
- Vs2022 has an issue where it could not get the correct Poco dependancies, and I think this is a problem in the pipeline. or well, I can test it next time I up my windows machine. So for now for windows we have the msys2 pipeline to validate.


- Mac make fails on a linker error. Which looks to be originated in libusb or svg. I recon it would be a good idea to fix both issues. 

Logs spawned in building libusb
```

In file included from struct 'libusb_device' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]/Users/ignited/Development/Environments/of_v0.12.0_osx_release/examples/templates/example_HelloLaser/src/ofApp.h:
4:
In file included from /Users/ignited/Development/Environments/of_v0.12.0_osx_release/addons/ofxLaser/src/ofxLaserManager.h:8:
In file included from /Users/ignited/Development/Environments/of_v0.12.0_osx_release/addons/ofxLaser/src/core/ofxLaserManagerBase.h:13:
struct libusb_device;In file included from 
/Users/ignited/Development/Environments/of_v0.12.0_osx_release/addons/ofxLaser/src/dacs/ofxLaserDacAssigner.h:^22
:
In file included from /Users/ignited/Development/Environments/of_v0.12.0_osx_release/addons/ofxLaser/src/dacs/ofxLaserDacManagerLaserdock.h:10:
In file included from /Users/ignited/Development/Environments/of_v0.12.0_osx_release/addons/ofxLaser/src/dacs/ofxLaserDacLaserdock.h:16:
/Users/ignited/Development/Environments/of_v0.12.0_osx_release/addons/ofxLaser/libs/laserdocklib/LaserdockDevice.h:/Users/ignited/Development/Environments/of_v0.12.0_osx_release/addons/ofxLaser/libs/libusb/include/libusb/libusb.h33::8997::1 : note: warning: previous use is here
struct 'libusb_device' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
class libusb_device;struct libusb_device;
```

The error spawned in SVG, which might be the real origin of the build failing

```
undef: _svgtiny_create
undef: _svgtiny_free
undef: _svgtiny_parse
Undefined symbols for architecture x86_64:
  "_svgtiny_create", referenced from:
      ofxSVGExtra::loadFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in ofxSvgExtra.o
  "_svgtiny_free", referenced from:
      ofxSVGExtra::loadFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in ofxSvgExtra.o
  "_svgtiny_parse", referenced from:
      ofxSVGExtra::loadFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in ofxSvgExtra.o
ld: symbol(s) not found for architecture x86_64

```
and a screenshot from the pipeline

Screenshot 2024-03-08 at 09 55 51


if you want to enable makefiles build testing for mac again, uncomment this line

[          # - {target: osx, opt: "makefiles"}
](https://github.com/sebleedelisle/ofxLaser/blob/5848deb62add93db0c07f1162cc48dd5b1b02e1e/.github/workflows/build-macos.yml#L20)

and if you want to enable vs2022, move it to the workflows folder.

I think it is save to say that you could remove the .appvenyor.yml and the link to appvenyor and replace it with a status check from github actions.

Also be aware that the pipelines run the pipeline as defined in its own branche.

I guess thats it. Feel free to hit me up when you need help or a coding rubber ducky.

**Pull request merged**
