### PR TITLE
fixes for oF 0.10 / master

### PR DESCRIPTION
**Pull request by npisanti**
as i work with the master version of oF, i had to make some changes to ofxLaser to make it work, that will make it work also with the latest stable (0.10). One of the things that could break something is that now `ofThread` doesn't use Poco, so i had to get the native thread and set the priority with pthread, that works on Linux and OSX (i tested only on linux). I also put an ifdef with some code to set the priority of the thread also on windows, but it still has to be tested. Poco is now included in ofxPoco, (that comes with oF), so i added that addon to the examples `addons.make` to make everything work.

As i said, i tested this with oF master (0.10), Debian Linux 9, an Etherdream 2 controller and a Laseworld DS-2000RGB laser.

### CODE REVIEW

**Comment by sebleedelisle** [comment]
Hey Nicola, this looks great! I'm in Toronto at the moment but I'll take a look when I get home. Would love to see what you've been doing with it!

**Comment by npisanti** [comment]
sure i'll keep you updated, let me know if everything works =)

**Comment by sebleedelisle** [comment]
OK I've merged, with a few other changes. I was hoping to keep backwards compatibility with oF 0.9 (at least for a little while) but unfortunately I couldn't work out how to only include an addon (ofxPoco) for 0.10 and not 0.9... no matter, I'll keep the stable branch for oF 0.9, master for 0.10. It compiles, but I haven't tested with a laser yet. Thanks for your contribution!

**Comment by npisanti** [comment]
if it is only for the source code, you can try:
```cpp
    #if (OF_VERSION_MINOR <= 9) // OF LEGACY for 0.9.8
    #include "ofxPoco.h"
    #endif
```
obviously people still have to manually delete ofxPoco from `addons.make` or import the projects with the project gen without including ofxPoco

**Comment by sebleedelisle** [comment]
yeah I meant the addons.make part... it would be kind of annoying to have to do that. But no worries, oF0.10 is where it's at :)

**Comment by npisanti** [comment]
ok, perfect! thank you very much =)

**Pull request merged**
