### PR TITLE
some updates

### PR DESCRIPTION
**Pull request by dimitre**
Hello @sebleedelisle I'm submitting some suggestions of change to make it run on macOS.
most of them related to the recent removal of ```using namespace std;```
I'm still having one issue with ofParameter guideImageColour
I'm trying to make it compile here to investigate projectGenerator issues.
Thanks

### CODE REVIEW

**Comment by sebleedelisle** [comment]
Hi Dimitre, thanks so much for this, although I worry that it may have been wasted, the dev branch is compiling for me with nightly, the main branch is a little out of date so I need to move the dev branch over some time soon. 

You wanna test the dev branch? 

thanks!

Seb

**Comment by dimitre** [comment]
Thanks, I've tested and it doesn't compile here. maybe ofxImGui should be updated

**Comment by sebleedelisle** [comment]
ah strange, mine seems to be compiling on OSX at least. I'll make sure I
have a clean download and try again.

**Comment by sebleedelisle** [comment]
OK I've merged this into main, and made some other minor changes, main now compiles in a relatively recent nightly on OSX. Thanks for your help with this!

**Pull request merged**
